# conf/config.yaml
defaults:
  - data
  - model
  - train
  - wandb
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}
    subdir: ${hydra.job.num}

output_dir: ${hydra:runtime.output_dir}
